### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by OthnielDona** [PythonBenin/PythonBenin.github.io#1]
- The Menu, on a phone's screen, does not drop down.
- The **About** button (link) does not work and ~~about.html~~ does not exist.
- The _constitution.html_ is a copy of the _index.html_ file.

**Comment by nioperas06** [comment]
Do you want to work on this issue?

**Comment by OthnielDona** [comment]
Yeah I'll look into it.

**Comment by OthnielDona** [comment]
I just created two pull request to solve the broken links and the missing page contents.
However the online version of the website needs to be updated so that the drop down nav in the responsive mode can work.
Thanks!

**Comment by nioperas06** [comment]
@kenn44 dis moi, une fois sur master, le site est mis a jour ou pas?

**Comment by OthnielDona** [comment]
Je crois oui. Je viens de vérifié, c'est à jour. Mais je ne comprends pas pourquoi je n'arrive toujours pas à défiler le menu sur mon téléphone. @nioperas06 est-ce que tu peux vérifier ?
