### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by nioperas06** [PythonBenin/PythonBenin.github.io#5]
En s'inspirant du site de ParisJS, nous allons reprendre le site de Python Benin, avec notamment les fonctionnalités ci-après:
- une page d'accueil présentant le(s) meetup(s) à venir ainsi que les précédents (infinite scroll);
- un champ de recherche, permettant de filtrer les meetups: voir la possibilité de le faire via Algolia;
- une page pour présenter le contenu de chaque meetup; les meetups passés avec les slides, etc...
- une page de FAQ;
- une page 'Proposer un sujet' qui affichera un formulaire avec les champs appropriés pour la soumission d'un sujet de meetup ou de conf;
- une page 'Partenaires' qui fera la liste des partenaires de Python Benin;
- Un menu de sélection de la langue: le site devra être disponible en FR et en EN;

**Comment by nioperas06** [comment]
![Screenshot from 2019-10-02 13-51-26](https://user-images.githubusercontent.com/11293401/66722087-89747700-ee01-11e9-8b16-48f11c73bb18.png)
![Screenshot from 2019-10-02 13-51-50](https://user-images.githubusercontent.com/11293401/66722088-8a0d0d80-ee01-11e9-842b-dac3f2ba345a.png)
![Screenshot from 2019-10-02 13-52-51](https://user-images.githubusercontent.com/11293401/66722089-8a0d0d80-ee01-11e9-901e-121a5a95f066.png)
![Screenshot from 2019-10-02 13-53-20](https://user-images.githubusercontent.com/11293401/66722091-8a0d0d80-ee01-11e9-9e3a-b58ba0e3fabe.png)
![Screenshot from 2019-10-02 13-53-33](https://user-images.githubusercontent.com/11293401/66722092-8aa5a400-ee01-11e9-8948-f1cc94434465.png)
![Screenshot from 2019-10-02 13-54-03](https://user-images.githubusercontent.com/11293401/66722093-8aa5a400-ee01-11e9-92bc-d095b2f2b36b.png)
![Screenshot from 2019-10-02 13-54-20](https://user-images.githubusercontent.com/11293401/66722094-8b3e3a80-ee01-11e9-8a54-7bfde28426f1.png)
![Screenshot from 2019-10-02 13-54-34](https://user-images.githubusercontent.com/11293401/66722095-8bd6d100-ee01-11e9-8fe6-22209f5b1749.png)
![Screenshot from 2019-10-02 13-57-35](https://user-images.githubusercontent.com/11293401/66722096-8c6f6780-ee01-11e9-9f2f-382b5a111060.png)
![Screenshot from 2019-10-02 13-58-00](https://user-images.githubusercontent.com/11293401/66722098-8c6f6780-ee01-11e9-96e2-efee325cccb5.png)
![Screenshot from 2019-10-02 13-59-09](https://user-images.githubusercontent.com/11293401/66722099-8d07fe00-ee01-11e9-9c4a-7b9064a70b64.png)
![Screenshot from 2019-10-02 13-59-29](https://user-images.githubusercontent.com/11293401/66722100-8da09480-ee01-11e9-97f3-3124b1614803.png)
![Screenshot from 2019-10-02 14-00-12](https://user-images.githubusercontent.com/11293401/66722102-8da09480-ee01-11e9-9ba2-4527980f54ac.png)
![Screenshot from 2019-10-02 14-06-38](https://user-images.githubusercontent.com/11293401/66722103-8e392b00-ee01-11e9-9da5-dc0d12d30162.png)

**Comment by nioperas06** [comment]
Stack choisie: Hugo, Netlify Forms, Algolia, etc...
On devra utiliser la branche `develop` afin de ne pas rendre indisponible le site actuel.

**Comment by thetallralph** [comment]
1. Serait-ce possible qu'on migre vers tailwind pour le CSS ?
2. Aussi, je me propose pour construire les "composants" de la page `home`

**Comment by nioperas06** [comment]
1. Tailwind :sweat_smile: je ne suis pas un gros fan, mais si @OthnielDona est partant on peut l'essayer.
2. Okay

**Comment by thetallralph** [comment]
So I have start exploring this header since it will be great to not be copy copy 😅.
Don't worry I will not be fancy fancy so could move fast...
![image](https://user-images.githubusercontent.com/5084657/67175451-05505f80-f3be-11e9-9316-bbd15757bbd3.png)

Let me know what you think about that.
_The thinking behind it was to make the "Propose a topic" button a bit more noticeable._

Oops je parlais Anglais 😅... Boff de toute façon vous me comprenez

**Comment by OthnielDona** [comment]
Tailwind... Ah ! Quand on est trop doué aussi la 😀. Si tu va te charger du composant. Nous somme là pour apprendre aussi.

**Comment by thetallralph** [comment]
Hello
Concernant le https://github.com/PythonBenin/PythonBenin.github.io/issues/5
J'essaye de faire un deuxième pull request après mon 2ème commit. Mais j'ai l'impression que mon commit est joint directement à l'ancien PR que j'avais fait (bref je ne sais pas encore comment ça marche vraiment vos affaire de PR là 😅) #6 
Bref, j'ai fini avec la structure globale, 
il nous reste encore :
 1. à ce qu'on s'entendent sur une optimale structure pour les datas (meetups, partners, talks authors,
 2. j'ai pas trouver comment utiliser des `functions` hugo à l'intérieur d'un fichier html ayant un `front matter`
3. Comment compter vous gérer le nombre de participants ?
4. (Lié au .3) Où seront hébergés les événements ?
5. Algolia et Netlyform ne sont pas encore intégré
6. La traduction n'est pas encore intégré non plus.

@nioperas06  ça serait top si on pouvait se fixer des deadlines et mieux répartir le projet pour aller plus vite

**Comment by nioperas06** [comment]
Hello @thetallralph je promets de finir la structure minimale ce soir. :+1:

**Comment by nioperas06** [comment]
Vous pouvez dès à présent voir toutes les modifications apportées sur ce [lien](https://eager-bhabha-001a03.netlify.com/).

**Comment by nioperas06** [comment]
1. Fait;
2. On va revenir sur ce probleme plsu tard.
3. Laissons tomber.
5. Netlify c'est bon.
 
J'ai effectuez certaines modifications. Si vous avez des questions, n'hésitez pas. Il reste:
- le design adapté aux téléphones mobiles et tablettes;
- la traduction;

Apres ces deux modifications, on pourra lancer la nouvelle version du site. Merci.

**Comment by thetallralph** [comment]
J'ai terminé avec l'adaptation du design aux téléphones mobiles et tablettes (Essayer de tester à vos niveaux pour voir)
Il reste que la traduction avant de procéder au lancement.

**Comment by nioperas06** [comment]
Je regarde ça ce week-end 😉

**Comment by nioperas06** [comment]
I definitely need to create a reminder via comment maybe something like Twitter's remind me this in x hours bot. Hello @sphinxxanxus

**Comment by ghost** [comment]
> I definitely need to create a reminder via comment maybe something like Twitter's remind me this in x hours bot. Hello @sphinxxanxus

Working on

**Comment by OthnielDona** [comment]
Slt les pythonista. Désolé de vous avoir laissé la plus grande part du boulot. J’ai été très pris ces quelque mois. I am back now. Je pourrais me charger de la traduction, mais je n’ai aucune idée de comment m’y prendre. Est-ce qu’il faut crée un répertoire ?

**Comment by nioperas06** [comment]
I'll review your work tonigth @OthnielDona :+1:

**Comment by nioperas06** [comment]
Good job guys!

**Comment by nioperas06** [comment]
Nous prenons généralement des phots aux différents meetups. Pensez-vous que c'est utile de proposer un album de chaque meetup? Si oui, que pouvons-nous utiliser pour simplifier la tâche? @thetallralph @OthnielDona

**Comment by nioperas06** [comment]
@OthnielDona  fixed! Le site est disponible ici https://optimistic-wilson-167567.netlify.com/

**Comment by nioperas06** [comment]
On doit rajouter un minimum de SEO sur le site, surtout pour le preview lors du partage sur les réseaux sociaux. Utiliser le site https://metatags.io/ pour voir le rendu actuel sur Facebook et Google par exemple. 
![Capture d’écran 2019-12-23 à 09 02 32](https://user-images.githubusercontent.com/11293401/71344550-202c8500-2563-11ea-885e-029f839c5165.png)

**Comment by nioperas06** [comment]
On doit juste rajouter des meta tags dans le head 😄

**Comment by OthnielDona** [comment]
Je supose qu'il faut le mettre dans **layouts/partials/head.html**.

Voici les meta tags 
```
<!-- Primary Meta Tags -->
<title>Python Benin</title>
<meta name="title" content="Python Benin">
<meta name="description" content="La communauté des utilisateurs du langage de programmation Python au Bénin">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://optimistic-wilson-167567.netlify.com/">
<meta property="og:title" content="Python Benin">
<meta property="og:description" content="La communauté des utilisateurs du langage de programmation Python au Bénin">
<meta property="og:image" content="">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://optimistic-wilson-167567.netlify.com/">
<meta property="twitter:title" content="Python Benin">
<meta property="twitter:description" content="La communauté des utilisateurs du langage de programmation Python au Bénin">
<meta property="twitter:image" content="">

```
Et ca ressemble a ca
![meta_tags_python_benin](https://user-images.githubusercontent.com/15000047/71957651-42bad100-31e6-11ea-8a91-a08231b0f621.png)

**Comment by nioperas06** [comment]
Oui, c'est bien ca :+1:

**Comment by nioperas06** [comment]
Tu peux faire un PR

**Comment by nioperas06** [comment]
Thank you guys.
